export const APP = {
  BOARD: {
    ROW_SIZE: 15,
    COL_SIZE: 15,
  },
  TIME_LIMIT: 300, // 5m
}

export const MESSAGE = {
  PLAYER_NOT_FOUND: "Player not found",
  ROOM_NOT_FOUND: "Room not found",
  SOMETHING_WENT_WRONG: "Something went wrong",
  GAME_OVER: "Game over",
  MISSING_PLAYER: "Missing player",
  MISSING_GAME: "Missing game",
  CAN_NOT_JOIN_ROOM: "Can not join room",
  SUCCESS: "Success",
}

export const EVENT = {
  REQUEST: "EVENT_REQUEST",
  RESPONSE: "EVENT_RESPONSE",
}

export const ACTION = {
  CREATE_PLAYER: "ACTION_CREATE_PLAYER",
  CREATE_PRIVATE_ROOM: "ACTION_CREATE_PRIVATE_ROOM",
  GAME_STARTED: "ACTION_GAME_STARTED",
  GAME_OVER: "ACTION_GAME_OVER",
  JOIN_PUBLIC_ROOM: "ACTION_JOIN_PUBLIC_ROOM",
  JOIN_PRIVATE_ROOM: "ACTION_JOIN_PRIVATE_ROOM",
  TURN_PLAYED: "ACTION_TURN_PLAYED",
}