export const BOARD_SIZE = 15;
export const WINNING_COUNT = 5;
export const MESSAGE = {
  PLAYER_NOT_FOUND: "Player not found",
  ROOM_NOT_FOUND: "Room not found",
  SOMETHING_WENT_WRONG: "Something went wrong",
  GAME_OVER: "Game over",
  MISSING_PLAYER: "Missing player",
  MISSING_GAME: "Missing game",
  CAN_NOT_JOIN_ROOM: "Can not join room",
  SUCCESS: "Success",
}

export const EVENT = {
  REQUEST: "EVENT_REQUEST",
  RESPONSE: "EVENT_RESPONSE",
}

export const ACTION = {
  CREATE_PLAYER: "ACTION_CREATE_PLAYER",
  CREATE_ROOM: "ACTION_CREATE_ROOM",
  GAME_STARTED: "ACTION_GAME_STARTED",
  GAME_OVER: "ACTION_GAME_OVER",
  FIND_RANDOM_ROOM: "ACTION_FIND_RANDOM_ROOM",
  FIND_ROOM: "ACTION_FIND_ROOM",
  TURN_PLAYED: "ACTION_TURN_PLAYED",
}